[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_nft_staking = "9wDvVzwpSAEzjmnPx53PH49PQEusbg4xruZPZa8UuxPw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
